In [7]:
import numpy as np
import sys
if "../" not in sys.path:
  sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv

In [8]:
env = GridworldEnv()

In [9]:
def policy_evaluation(policy, env, discount_rate=1.0, theta=0.00001):
    V = np.zeros(env.nS)
    
    while True:
        delta = 0
        for s in range(env.nS):
            v = V[s]
            new_val = 0
            for a, a_prob in enumerate(policy[s]):
                for prob, next_state, reward, done in env.P[s][a]:
                    new_val += a_prob * prob * (reward + discount_rate * V[next_state])
            V[s] = new_val
            delta = max(delta, np.abs(v - V[s]))
        if delta < theta:
            break
    return V

In [10]:
random_policy = np.ones((env.nS, env.nA)) / env.nA
v = policy_evaluation(random_policy, env)

In [11]:
print(v)

[  0.         -13.99993529 -19.99990698 -21.99989761 -13.99993529
 -17.9999206  -19.99991379 -19.99991477 -19.99990698 -19.99991379
 -17.99992725 -13.99994569 -21.99989761 -19.99991477 -13.99994569
   0.        ]


In [12]:
print(v.reshape(env.shape))

[[  0.         -13.99993529 -19.99990698 -21.99989761]
 [-13.99993529 -17.9999206  -19.99991379 -19.99991477]
 [-19.99990698 -19.99991379 -17.99992725 -13.99994569]
 [-21.99989761 -19.99991477 -13.99994569   0.        ]]
